### PR TITLE
Remove flaky specs

### PR DESCRIPTION
**Pull request by sarahraqueld**
These tests is failing intermittently on CI, and so I'm removing it until we have a better solution.

### CODE REVIEW

**Comment by FerPerales** [comment]
Wondering if the test that is failing is also a flaky one 🤔

**Comment by sarahraqueld** [comment]
> Wondering if the test that is failing is also a flaky one 🤔

Seems like it! Removed it as well

**Review by FerPerales — APPROVED** [review]

**Comment by littleforest** [comment]
I think it was a different one that was flaky. The one that returns ["Medical Assistant", "Medical Assistant II", "Admin Assistant"].

**Comment by littleforest** [comment]
Oh nevermind, the whole file got removed.

**Review by littleforest — APPROVED** [review]

**Pull request merged**
