### PR TITLE
add afterparty task to import 2000, 2006, 2009, and 2010

### PR DESCRIPTION
**Pull request by crystal-williams-brown**
Asana ticket: https://app.asana.com/0/1203289004376659/1205644361039896/f

### CODE REVIEW

**Comment by crystal-williams-brown** [comment]
I have issues with the docker image for elasticsearch 8 not working out of the box with some of our population files from after party. Because of this I'm not able to run `rake after_party:run` successfully. If your dev environment doesn't have any elasticsearch issues, please check out this prior and run `rake after_party:run` to if if the changes in this PR work properly.

**Review by littleforest — COMMENTED** [review]
@crystal-williams-brown this looks really good except that there are multiple header rows on the files so that the script isn't able to read in the files correctly. Can you clean up the file headers?

**Review by littleforest — CHANGES_REQUESTED** [review]
Modify file headers so script works correctly.

**Review by littleforest — APPROVED** [review]
:shipit:

**Pull request merged**
