### PR TITLE
Upgrade Administrate to 1.0.0beta

### PR DESCRIPTION
**Pull request by littleforest**
This upgrades Administrate to the 1.0 beta version. I removed the customized layout where we were bringing in Flowbite and Tailwind since it was messing up some of the default Administrate styling. I used a regular select drop-down for the Redacted filter on the Imports page.

Screenshot 2024-05-28 at 10 05 32 AM

### CODE REVIEW

**Comment by littleforest** [comment]
@FerPerales this is ready for review.

**Review by FerPerales — APPROVED** [review]
Such a shame we have to remove the styling 😢 

LGTM

**Comment by littleforest** [comment]
> Such a shame we have to remove the styling

Were you being facetious? I couldn't see what customized styling we had in here that was actually being used anymore.

**Comment by FerPerales** [comment]
> > Such a shame we have to remove the styling
> 
> Were you being facetious? I couldn't see what customized styling we had in here that was actually being used anymore.

No. I mean the flowbite UI looks good, but if using it is causing issues with having administrate updated, I'd rather us getting rid of it

**Comment by littleforest** [comment]
Closing in favor of #804. I removed Tailwind and fixed some issues with Flowbite and it seems to be working okay.

**Pull request closed without merging**
